Make directory creation return EROFS, not ENOSYS
Similar to 4dd415e061ffc6403f9eb7965f15d5a1b8c3760e

We noticed this because pytest only handles EROFS
https://github.com/pytest-dev/pytest/blob/84e59af8c829de659efb339d5a9c7cec98eee719/src/_pytest/assertion/rewrite.py#L1174

Before
```console
$ python3 -c 'import pathlib; pathlib.Path("a").touch()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python-3.11/lib/python3.11/pathlib.py", line 1108, in touch
    fd = os.open(self, flags, mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: 'a'

$ python3 -c 'import pathlib; pathlib.Path("a").mkdir()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python-3.11/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
OSError: [Errno 38] Function not implemented: 'a'
```

After
```console
$ python3 -c 'import pathlib; pathlib.Path("a").mkdir()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python-3.11/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: 'a'
```